// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	user "qiniuyun/backend/app/internal/handler/user"
	"qiniuyun/backend/app/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Token},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/captcha",
					Handler: user.SendCaptchaHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/login",
					Handler: user.LoginHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/refresh",
					Handler: user.RefreshTokenHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/register",
					Handler: user.RegisterHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/user/:id",
					Handler: user.GetUserHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/user/name",
					Handler: user.GetUserByNameHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPut,
					Path:    "/user",
					Handler: user.UpdateUserinfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/user/password",
					Handler: user.ChangePwdHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api"),
	)
}
