// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	character "qiniuyun/backend/app/internal/handler/character"
	chat "qiniuyun/backend/app/internal/handler/chat"
	user "qiniuyun/backend/app/internal/handler/user"
	"qiniuyun/backend/app/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/upload/token",
					Handler: uploadTokenHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/user/tags",
					Handler: getUserTagsHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/tags",
				Handler: getTagsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/character",
					Handler: character.NewCharacterHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/character",
					Handler: character.GetCharacterHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/session",
					Handler: chat.NewSessionHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/session",
					Handler: chat.GetSessionHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/chat/:session_id",
				Handler: chat.ChatHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Token},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/captcha",
					Handler: user.SendCaptchaHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/login",
					Handler: user.LoginHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/refresh",
					Handler: user.RefreshTokenHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/register",
					Handler: user.RegisterHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/user/:id",
					Handler: user.GetUserHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/user/name",
					Handler: user.GetUserByNameHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPut,
					Path:    "/user",
					Handler: user.UpdateUserinfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/user/password",
					Handler: user.ChangePwdHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api"),
	)
}
