version: '3.7'
services:
  qdrant:
    image: qdrant/qdrant:v1.12.3
    container_name: qdrant
    ports:
      - "6333:6333"   # REST API
      - "6334:6334"   # gRPC API
    volumes:
      - ./qdrant_storage:/qdrant/storage
    restart: unless-stopped

  embedding-service:
    build: ./embedding_service
    container_name: embedding-service
    ports:
      - "5000:5000"