version: '3.7'
services:
  zookeeper:
    image: zookeeper
    ports:
      - 2181:2181

  kafka-manager:
    image: sheepkiller/kafka-manager
    container_name: "kafka-manager"
    ports:
      - "9000:9000"
    environment:
      TZ: CST-8
      # 指定zookeeper地址
      ZK_HOSTS: zookeeper:2181

  kafka1:
    image: wurstmeister/kafka
    container_name: kafka1
    expose:
      - "9999"       # JMX-PORT   用于监控kafka集群
    ports:
      - "9093:9093"
      - "9999:9999"
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: 172.21.192.1:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.21.192.1:9093
      JMX_PORT: 9999
    volumes:
      - /home/ubuntu/kafka_data:/kafka
      - /var/run/docker.sock:/var/run/docker.sock

  qdrant:
    image: qdrant/qdrant:v1.12.3
    container_name: qdrant
    ports:
      - "6333:6333"   # REST API
      - "6334:6334"   # gRPC API
    volumes:
      - ./qdrant_storage:/qdrant/storage
    restart: unless-stopped