version: '3.7'
services:
  qdrant:
    image: qdrant/qdrant:v1.12.3
    container_name: qdrant
    ports:
      - "6333:6333"   # REST API
      - "6334:6334"   # gRPC API
    volumes:
      - ./qdrant_storage:/qdrant/storage
    restart: unless-stopped

  embedding-service:
    build: ./embedding_service
    container_name: embedding-service
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - mysql

  redis:
    image: redis:7.2
    container_name: redis
    command: ["redis-server", "--requirepass", "pass"]
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: roletalk
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart: unless-stopped