// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"fmt"
	"time"

	"github.com/SpectatorNan/gorm-zero/gormc"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"gorm.io/gorm"
)

var (
	cacheRoletalkSessionIdPrefix = "cache:roletalk:session:id:"
)

type (
	sessionModel interface {
		Insert(ctx context.Context, tx *gorm.DB, data *Session) error

		FindOne(ctx context.Context, id int64) (*Session, error)
		Find(ctx context.Context, cursor int64, pageSize int64) ([]*Session, error)
		FindByQuery(ctx context.Context, cursor int64, pageSize int64, query map[string]interface{}) ([]*Session, error)
		FuzzyFind(ctx context.Context, cursor int64, pageSize int64, title string, keyword string) ([]*Session, error)

		Update(ctx context.Context, tx *gorm.DB, data *Session) error

		Delete(ctx context.Context, tx *gorm.DB, id int64) error
		Transaction(ctx context.Context, fn func(db *gorm.DB) error) error
	}

	defaultSessionModel struct {
		gormc.CachedConn
		table string
	}

	Session struct {
		Id          int64     `gorm:"column:id"`
		CharacterId int64     `gorm:"column:character_id"` // 关联的角色ID
		UserId      int64     `gorm:"column:user_id"`      // 用户ID
		Title       string    `gorm:"column:title"`        // 会话标题，例如第一句话或摘要
		CreatedAt   time.Time `gorm:"column:created_at"`
		UpdatedAt   time.Time `gorm:"column:updated_at"`
	}
)

func (Session) TableName() string {
	return "`session`"
}

func newSessionModel(conn *gorm.DB, c cache.CacheConf) *defaultSessionModel {
	return &defaultSessionModel{
		CachedConn: gormc.NewConn(conn, c),
		table:      "`session`",
	}
}

func (m *defaultSessionModel) Insert(ctx context.Context, tx *gorm.DB, data *Session) error {

	err := m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(&data).Error
	}, m.getCacheKeys(data)...)
	return err
}

func (m *defaultSessionModel) FindOne(ctx context.Context, id int64) (*Session, error) {
	roletalkSessionIdKey := fmt.Sprintf("%s%v", cacheRoletalkSessionIdPrefix, id)
	var resp Session
	err := m.QueryCtx(ctx, &resp, roletalkSessionIdKey, func(conn *gorm.DB, v interface{}) error {
		return conn.Model(&Session{}).Where("`id` = ?", id).First(&resp).Error
	})
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSessionModel) Update(ctx context.Context, tx *gorm.DB, data *Session) error {
	old, err := m.FindOne(ctx, data.Id)
	if err != nil && err != ErrNotFound {
		return err
	}
	clearKeys := append(m.getCacheKeys(old), m.getNewModelNeedReloadCacheKeys(data)...)
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(data).Error
	}, clearKeys...)
	return err
}

func (m *defaultSessionModel) getCacheKeys(data *Session) []string {
	if data == nil {
		return []string{}
	}
	roletalkSessionIdKey := fmt.Sprintf("%s%v", cacheRoletalkSessionIdPrefix, data.Id)
	cacheKeys := []string{
		roletalkSessionIdKey,
	}
	cacheKeys = append(cacheKeys, m.customCacheKeys(data)...)
	return cacheKeys
}

func (m *defaultSessionModel) Delete(ctx context.Context, tx *gorm.DB, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		if err == ErrNotFound {
			return nil
		}
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Delete(&Session{}, id).Error
	}, m.getCacheKeys(data)...)
	return err
}

func (m *defaultSessionModel) Transaction(ctx context.Context, fn func(db *gorm.DB) error) error {
	return m.TransactCtx(ctx, fn)
}

func (m *defaultSessionModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheRoletalkSessionIdPrefix, primary)
}

func (m *defaultSessionModel) queryPrimary(conn *gorm.DB, v, primary interface{}) error {
	return conn.Model(&Session{}).Where("`id` = ?", primary).Take(v).Error
}
